[Desktop Entry]
Name=Leopardish
Type=X-GNOME-Metatheme
Comment=

[X-GNOME-Metatheme]
GtkTheme=Mac Final
MetacityTheme=Leopardish
IconTheme=Fedora
GtkColorScheme=fg_color:#000000000000,bg_color:#bebebebebebe,text_color:#1a1a1a1a1a1a,base_color:#ffffffffffff,selected_fg_color:#ffffffffffff,selected_bg_color:#737388889999,tooltip_fg_color:#000000000000,tooltip_bg_color:#f5f5f5f5b5b5
CursorTheme=default
CursorSize=18
NotificationTheme=nodoka
